[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.tokenizer",
  "php83Extensions.xml",
  "php83Extensions.curl",
  "php83Extensions.fileinfo",
  "php83Extensions.bcmath",
  "php83Extensions.openssl",
  "curl",
  "unzip"
]

[phases.build]
cmds = [
  # Install Composer manually
  "curl -sS https://getcomposer.org/installer | php",
  "mv composer.phar /usr/local/bin/composer",
  
  # Laravel setup
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "cp .env.example .env",  # Make sure .env exists
  "php artisan key:generate",
  "php artisan optimize:clear",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan storage:link",
  "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
